spring:
  profiles:
    active: local
  application:
    name: eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LenoXian/config_repo
          force-pull: true
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  config: classpath:eureka-logback.xml

